//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GüzellikmerkeziOtomasyon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class localEntities : DbContext
    {
        public localEntities()
            : base("name=localEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<calisan> calisan { get; set; }
        public virtual DbSet<hizmetler> hizmetler { get; set; }
        public virtual DbSet<müşteriler> müşteriler { get; set; }
        public virtual DbSet<Seanslar> Seanslar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual int sp_EkleSeans(string ad, string soyad, Nullable<System.DateTime> tarih, Nullable<System.TimeSpan> saat)
        {
            var adParameter = ad != null ?
                new ObjectParameter("Ad", ad) :
                new ObjectParameter("Ad", typeof(string));
    
            var soyadParameter = soyad != null ?
                new ObjectParameter("Soyad", soyad) :
                new ObjectParameter("Soyad", typeof(string));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            var saatParameter = saat.HasValue ?
                new ObjectParameter("Saat", saat) :
                new ObjectParameter("Saat", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EkleSeans", adParameter, soyadParameter, tarihParameter, saatParameter);
        }
    }
}
